---
- name: "Ensure deploy dir exists"
  file:
    path: "{{ testops_deploy_path }}"
    state: directory
    mode: "0740"

- name: "Copy docker compose config"
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ testops_deploy_path }}/docker-compose.yml"
    mode: '0640'

- name: "Copy env"
  template:
    src: "env.j2"
    dest: "{{ testops_deploy_path }}/.env"
    mode: '0640'

- name: "Deploy testops"
  docker_compose:
    project_src: "{{ testops_deploy_path }}"